name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        components: clippy, rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --target=x86_64-unknown-linux-gnu

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        components: clippy, rustfmt
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy --verbose
